---
title: "Assignment 4"
author: "Gracie White"
date: "November 12, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Packages and datasets
```{r, include = FALSE}
# Install necessary packages
library(tidyverse)
library(pwr)
library(knitr)
library(kableExtra)
library(plotly)
library(extrafont)
library(ggrepel)
library(vcdExtra)

# Load Datasets
lobster_size_df <- read_csv("lobster_size_abundance.csv")
traps_df <- read_csv("lobster_traps.csv")

```
##1. Initial Observations
```{r}
# Fishing Pressure
# First, filter the data so we only keep relevant info
traps5_df <- traps_df %>%
  select(YEAR, MONTH, FISHING_SEASON, SITE, TRAPS) %>%
  filter(SITE == "CARP" | SITE == "AQUE" | SITE == "IVEE" | SITE == "NAPL" | SITE == "MOHK") %>%
  group_by(SITE, YEAR) 
  
# Summary table of lobster traps each year by site  
trap5_sumtable <- summarize(traps5_df, med_traps = median(TRAPS), max_traps = max(TRAPS), mean_traps = mean(TRAPS), sd_traps = sd(TRAPS), sample_size = length(TRAPS)) %>% 
  mutate(MPA = ifelse(SITE == "IVEE" | SITE == "NAPL", "MPA", "No MPA"))

# Line graph of mean lobster traps by year for each site
traps_line_g <- ggplot(trap5_sumtable, aes(x = YEAR, y = mean_traps, group = SITE, color = SITE)) +
  geom_line(size = 1, alpha = 0.8, aes(linetype = MPA)) +
  theme_classic() +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) +
  labs(x = "Year", y = "Mean Lobster Traps", title = "Average Lobster Traps (2012-2017)")

traps_line_g

# looks like fishing pressure is decreasing over time. The drop after 2016 is probably a result of the decreased abundance seen in the next figure? Note that there are no traps in the MPA sites. 
```
######Abundance Observations
```{r}

# Filter sites 
lobcount_allyears_df <- lobster_size_df %>% 
  filter(SITE == "AQUE"| SITE == "NAPL"| SITE == "MOHK"| SITE == "IVEE"| SITE == "CARP", COUNT != "0") %>% 
  select(YEAR, SITE, COUNT) %>% 
  group_by(SITE, YEAR)
#add up all lobster observations by site and year
lobcount <- aggregate(COUNT~SITE+YEAR, data = lobcount_allyears_df, sum) 
#Create column to specify if site is an MPA or not  
lobcount <- mutate(lobcount, MPA = ifelse(SITE == "IVEE" | SITE == "NAPL", "MPA", "No MPA")) %>% 
  group_by(SITE, YEAR)

#line graph of abundance by site
abundance_line_g <- ggplot(lobcount, aes(x = YEAR, y = COUNT, group = SITE, color = SITE)) +
  geom_line(size = 1, alpha = 0.8, aes(linetype = MPA)) +
  labs(x = "Year", y = "Number of Lobsters Observed", title = "Spiny Lobster Abundance in the Santa Barbara Channel (2012-2017)") +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) +
  theme_classic()

abundance_line_g
#Abundance has recently increased in IVEE and CARP, but decreased or stayed similar at other sites. Why is there a peak in 2015, and an overall decrease in 2016? Was there an event that we should be aware of? Why is CARP increasing so much when it's not an MPA, and conversely, why is the NAPL MPA decreasing? Perhaps an El Niño event? A change in fishery regulations? A lobster disease? 
```



####Part 2. Compare Mean Lobster Size by Site in 2017
```{r}
# Reformat size data into tidy format
# Filter sites and omit counts of "0"
lsize_sites_df <- lobster_size_df %>% 
  filter(SITE == "AQUE"| SITE == "NAPL"| SITE == "MOHK"| SITE == "IVEE"| SITE == "CARP", COUNT != "0", YEAR == "2017") %>% 
  select(YEAR, SITE, SIZE, COUNT)


# Expand Rows
lsize_expanded <- uncount(lsize_sites_df, weights = COUNT, .remove = FALSE)

```


```{r}
# One variable (carapace length (mm)), 5 factors
# Perform one-sided ANOVA

# Identify hypotheses
# H0: Means across all groups are equal
# HA: At least two group means differ significantly
size_aov <- aov(SIZE ~ SITE, data = lsize_expanded)
summary(size_aov)

# Sample means are this different because they were most likely drawn for different population
# H0: Means across all groups are equal
# HA: At least two group means differ significantly

# p-value is <0.05 -> Reject the null.  There is a significant difference in means.  
# Sample means are this different because they were most likely drawn for different population
# Use post-hoc testing to see which sites differ

# Identify hypotheses
# H0:  There is no significant difference in pairwise means
# HA: There is a significant difference in pairwise means
size_pht <- TukeyHSD(size_aov)
size_pht

# p-value is <0.05 for sites (NAPL-CARP), (NAPL-IVEE)
# Reject the null for sites (NAPL-CARP), (NAPL-IVEE)

# Create a box-plot for visual mean comparison
size_bp <- ggplot(lsize_expanded, aes(x = SITE, y = SIZE)) +
  geom_boxplot(aes(color = SITE)) +
  ggtitle("Lobster Carapace Lengths at 5 LTER Sites in the Santa Barbara Channel, 2017") +
  xlab("Site") +
  ylab("Carapace Length (mm)") +
  theme_classic() +
  scale_colour_brewer("Site", palette = "Set2")
size_bp

# Create a data summary table to compare means
size_sum_df <- lsize_expanded %>% 
  group_by(SITE) %>% 
  summarize(count = n(), 
    mean = mean(SIZE),
    sd = sd(SIZE))
size_sum_df
```

####Part 3. Changes in lobster size at MPA and non-MPA sites (comparing only 2012 and 2017 sizes)
```{r}
# MPA Sites: IVEE, NAPL
# Non-MPA Sites: IVEE, NAPL

# Reformat size data into tidy format
# Filter sites and omit counts of "0"
lsize_sitesmpa_df <- lobster_size_df %>% 
  filter(SITE == "AQUE"| SITE == "NAPL"| SITE == "MOHK"| SITE == "IVEE"| SITE == "CARP", COUNT != "0",
         YEAR == "2012"| YEAR == "2017") %>% 
  select(YEAR, SITE, SIZE, COUNT)


# Expand Rows
lsizempa_expanded <- uncount(lsize_sitesmpa_df, weights = COUNT, .remove = FALSE)

# For exploration purposes, perhaps a facet-wrapped histogram of size distributions?

size_hist <- ggplot(lsize_expanded, aes(x = SIZE)) +
  geom_histogram(bins = 15, aes(fill = SITE)) +
  facet_wrap(~ SITE, scale = "free") + 
  theme_classic() +
  theme(legend.position = "none") + 
  scale_y_continuous(expand = c(0,0))

size_hist

# Use t-tests to compare means


```

