---
title: "Sandy"
author: "Sandra Fogg"
date: "11/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Install packages
library(tidyverse)
library(pwr)
library(knitr)
library(kableExtra)
library(plotly)
library(extrafont)
library(ggrepel)
library(vcdExtra)
library(colorspace)
library(RColorBrewer)

# Read Datasets
lobster_size_df <- read_csv("lobster_size_abundance.csv")
traps_df <- read_csv("lobster_traps.csv")

# Reformat size data into tidy format
# Filter sites and omit counts of "0"
lsize_sites_df <- lobster_size_df %>% 
  filter(SITE == "AQUE"| SITE == "NAPL"| SITE == "MOHK"| SITE == "IVEE"| SITE == "CARP", COUNT != "0", YEAR == "2017") %>% 
  select(YEAR, SITE, SIZE, COUNT)

View(lsize_sites_df)

lsize_expanded <- uncount(lsize_sites_df, weights = COUNT, .remove = FALSE)
View(lsize_expanded)

```

####Part 2. Compare Mean Lobster Size by Site in 2017
```{r}
# One variable (carapace length (mm)), 5 factors
# Perform one-sided ANOVA

# Identify hypotheses
# H0: Means across all groups are equal
# HA: At least two group means differ significantly
size_aov <- aov(SIZE ~ SITE, data = lsize_expanded)
summary(size_aov)

# Sample means are this different because they were most likely drawn for different population
# H0: Means across all groups are equal
# HA: At least two group means differ significantly

# p-value is <0.05 -> Reject the null.  There is a significant difference in means.  
# Sample means are this different because they were most likely drawn for different population
# Use post-hoc testing to see which sites differ

# Identify hypotheses
# H0:  There is no significant difference in pairwise means
# HA: There is a significant difference in pairwise means
size_pht <- TukeyHSD(size_aov)
size_pht

# p-value is <0.05 for sites (NAPL-CARP), (NAPL-IVEE)
# Reject the null for sites (NAPL-CARP), (NAPL-IVEE)

# Create a box-plot for visual mean comparison
size_bp <- ggplot(lsize_expanded, aes(x = SITE, y = SIZE)) +
  geom_boxplot(aes(color = SITE)) +
  ggtitle("Lobster Carapace Lengths at 5 LTER Sites in the Santa Barbara Channel, 2017") +
  xlab("Site") +
  ylab("Carapace Length (mm)") +
  theme_classic() +
  scale_colour_brewer("Site", palette = "Set2")
size_bp

# Create a data summary table to compare means
size_sum_df <- lsize_expanded %>% 
  group_by(SITE) %>% 
  summarize(count = n(), 
    mean = mean(SIZE),
    sd = sd(SIZE))
size_sum_df
```

Mean carapace lengths (mm) of lobsters differed significantly between sites NAPL and CARP, as well as between sites NAPL and IVEE (one-way anova, F(df) = statistic, *p* = `r {round(size_pht$p.value, 3)}` , $\alpha$ = 0.05 with post-hoc Tukey's HSD, $\alpha$ = 0.05)
```

